### ISSUE TITLE
add service name to main layout

### ISSUE THREAD

**Issue by BretFisher** [mikesir87/swarm-viz#9]
Idea: rather than having the image name and container ID listed in main view "container box", it seems more intuitive to me to have the task name as the title of the box, with the image name below it. Individual container ID's aren't relevant enough IMO to warrant being on the main view, but are still valuable in popup.

**Comment by mikesir87** [comment]
Makes total sense. I’ll make that update. For demos, I’ve frequently pulled an ID from the UI and killed that container, showing the self healing aspects. But, that could easily be done by pulling the ID from the modal too.

**Comment by mikesir87** [comment]
Just finished. Should be out shortly. Sorry it took so long 👍
